name: Actions Workflow Test
on: [push]
jobs: 
  run-github-actions:
    runs-on: [ubuntu-latest]
    steps:
      - name: Simple JS Action
        id: greetId
        uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: Bob
      - name: echo greet ID
        run: echo "${{steps.greetId}}