name: "My Node Container"
on: push
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:13.5.0-alpine3.10
    steps: 
      - name: Log Node Version
        run: |
          echo 'Saving results to myfile.txt'
          npm -v > myfile.txt
          echo 'Done running command'

    