name: My first workflow
on: [push]

jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "YoYo"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python jobs
        run: | 
          import platform
          print(platform.processor())
          