name: Who Am I
on: [push, pull_request]
jobs: 
  whereami:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: List entire directory contents
        run: |
          ls -a
      - name: List all my env vars
        run: printenv
  another-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Run github stuff
        run: |
          git clone git@github:$GITHUB_REPOSITORY
          git checkout $GITHUB_SHA