name: Who Am I
on: [push]
jobs: 
  whereami:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Simple JS Action
        run: |
          ls -a